version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prisma
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multitenant
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: